// <auto-generated />
using System;
using ContaBancaria.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace conta_bancaria_api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190909133458_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ContaBancaria.API.Domain.Models.ContaCorrente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<decimal>("Saldo")
                        .HasColumnName("saldo")
                        .HasColumnType("DECIMAL(18,6)");

                    b.HasKey("Id");

                    b.ToTable("contas");
                });

            modelBuilder.Entity("ContaBancaria.API.Domain.Models.Transacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("ContaCorrenteId")
                        .HasColumnName("conta_corrente_id");

                    b.Property<DateTime>("DataHora")
                        .HasColumnName("data_hora")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("descricao")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<long?>("ParentId")
                        .HasColumnName("parent_id");

                    b.Property<decimal>("SaldoAnterior")
                        .HasColumnName("saldo_anterior")
                        .HasColumnType("DECIMAL(18,6)");

                    b.Property<decimal>("SaldoFinal")
                        .HasColumnName("saldo_final")
                        .HasColumnType("DECIMAL(18,6)");

                    b.Property<byte>("Tipo")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasColumnName("valor")
                        .HasColumnType("DECIMAL(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("ContaCorrenteId");

                    b.HasIndex("ParentId");

                    b.ToTable("transacoes");
                });

            modelBuilder.Entity("ContaBancaria.API.Domain.Models.Transacao", b =>
                {
                    b.HasOne("ContaBancaria.API.Domain.Models.ContaCorrente", "ContaCorrente")
                        .WithMany("Transacoes")
                        .HasForeignKey("ContaCorrenteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ContaBancaria.API.Domain.Models.Transacao", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });
#pragma warning restore 612, 618
        }
    }
}
