// <auto-generated />
using System;
using ContaBancaria.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace conta_bancaria_api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190831165434_CreateTransacao")]
    partial class CreateTransacao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ContaBancaria.API.Domain.Models.ContaCorrente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Saldo");

                    b.HasKey("Id");

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("ContaBancaria.API.Domain.Models.Transacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("ContaCorrenteId");

                    b.Property<DateTime>("DataHora")
                        .HasColumnName("data_hora")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("descricao")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<decimal>("SaldoAnterior")
                        .HasColumnName("saldo_anterior")
                        .HasColumnType("DECIMAL(18,6)");

                    b.Property<decimal>("SaldoFinal")
                        .HasColumnName("saldo_final")
                        .HasColumnType("DECIMAL(18,6)");

                    b.Property<byte>("Tipo")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasColumnName("valor")
                        .HasColumnType("DECIMAL(18,6)");

                    b.HasKey("Id");

                    b.ToTable("transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
